---

- name: Install NFS
  become: true
  ansible.builtin.package:
    name: nfs-kernel-server
    state: present
  notify:
    - nfs.export
    - nfs.restart

- name: Setup NFS exports
  become: true
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    mode: "{{ perms_file_private }}"
    owner: "{{ user_root }}"
    group: "{{ group_root }}"
  notify:
    - nfs.export
    - nfs.restart