---
- tags:
    - facts
  block:
    - name: Check if it's a WSL deployment
      ansible.builtin.command:
        cmd: which wsl.exe
      failed_when: false
      changed_when: false
      register: wsl
    - name: Get actual user shell from passwd file
      ansible.builtin.shell:
        cmd: >-
          cat /etc/passwd
          | grep {{ ansible_env.USER }}
          | rev | cut --delimiter=":" --fields=1 | rev
      register: shell
      changed_when: false
    - name: Get logged in user's group name
      ansible.builtin.command:
        cmd: id -gn
      failed_when: false
      changed_when: false
      register: group
    - name: Register facts
      ansible.builtin.set_fact:
        is_wsl: "{{ wsl.rc == 0 }}"
        user_group: "{{ group.stdout }}"
        user_shell: "{{ shell.stdout }}"