- name: Apply home-manager customizations
  listen: home_manager.switch
  environment: "{{ {} | ansible.builtin.combine(environment_default) }}"
  ansible.builtin.command:
    cmd: "home-manager init --switch '{{ home_manager_root }}'"
