- name: Init home-manager
  listen: home_manager_init
  environment:
    PATH: "{{ env_path }}"
  ansible.builtin.command:
    cmd: home-manager init
  register: init
  changed_when: "{{ init.stdout_lines | map('match', 'Created') is any }}"
- name: Apply home-manager customizations
  listen: home_manager_switch
  environment:
    PATH: "{{ env_path }}"
  ansible.builtin.command:
    cmd: home-manager switch