---

- name: Install Nextcloud AIO
  become: true
  ansible.builtin.command:
    cmd: 
      docker run \
      --sig-proxy=false \
      --name nextcloud-aio-mastercontainer \
      --restart always \
      --publish 8080:8080 \
      --env APACHE_PORT=11000 \
      --env APACHE_IP_BINDING=0.0.0.0 \
      --env NEXTCLOUD_DATADIR="{{ path_app_data }}/nextcloud" \
      --env AIO_DISABLE_BACKUP_SECTION=true \
      --env NEXTCLOUD_MOUNT="/storage" \
      --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
      --volume /var/run/docker.sock:/var/run/docker.sock:ro \
      nextcloud/all-in-one:latest