---

- name: Install caddy service file
  ansible.builtin.template:
    src: templates/caddy.service.j2
    dest: "/etc/systemd/system/caddy.service"
    owner: root
    group: root
    mode: "{{ perms_file_default }}"

- name: Ensure Caddyfile target dir exists
  ansible.builtin.file:
    path: "{{ path_config }}"
    state: directory
    owner: root
    group: root
    mode: "{{ perms_dir_default }}"

- name: Template and install Caddyfile
  ansible.builtin.template:
    src: templates/Caddyfile.j2
    dest: "{{ path_config_file }}"
    owner: root
    group: root
    mode: "{{ perms_file_default }}"
    validate: caddy fmt --overwrite
  notify: caddy.restart

- name: Enable caddy service
  ansible.builtin.systemd:
    name: caddy
    enabled: true
    state: reloaded
    daemon_reload: true
