- name: Remove Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: absent

- name: Remove Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: absent

- name: Uninstall docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: absent

- name: Uninstall Docker Module for Python
  ansible.builtin.pip:
    name: absent
