- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Ensure keyring dir exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    mode: "{{ perms_dir_private }}"
    state: directory
  become: true

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ os_id }}/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  become: true

- name: Add Docker Repository
  ansible.builtin.shell:
    cmd: >
      echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ os_id }} "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable"
      | tee /etc/apt/sources.list.d/docker.list
  become: true

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: true
  become: true

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker
  become: true

- name: Create docker daemon config
  ansible.builtin.template:
    src: templates/daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: "{{ perms_file_default }}"
  become: true