---

- name: Install container backend
  ansible.builtin.include_tasks:
    file: "backend-install.yml"
    apply:
      become: true
      tags:
        - install
        - initial

- name: Template application files
  ansible.builtin.include_tasks:
    file: template-app-files.yml
    apply:
      tags:
        - specific

- name: Template compose files
  with_fileglob:
    - "templates/compose/*.j2"
  loop_control:
    loop_var: file
  ansible.builtin.template:
    src: "{{ file }}"
    dest: "~/{{ file | basename | replace('.j2', '') }}"
  notify: compose.update
