---

- name: Get OS ID
  ansible.builtin.shell:
    cmd: >- 
      cat /etc/os-release
      | grep ^ID=
      | cut --delimiter="=" --fields=2
  register: os
  changed_when: false

- name: Register OS ID
  ansible.builtin.set_fact:
    os_id: "{{ os.stdout }}"

- name: Ensure containers are present
  ansible.builtin.include_tasks:
    file: "install.yml"
  when: state == 'present'

- name: Ensure containers are absent
  ansible.builtin.include_tasks:
    file: "uninstall.yml"
  when: state == 'absent'
