---

- name: Ensure containers are present
  ansible.builtin.include_tasks:
    file: "install.yml"
  when: state == 'present'

- name: Ensure containers are absent
  ansible.builtin.include_tasks:
    file: "uninstall.yml"
  when: state == 'absent'
