---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

language: en
layout:
  Main:
    style: row
    columns: 4
    header: false
  Media:
    style: row
    columns: 4
  Storage:
  Other:
