---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

layout:
  Main:
    style: row
    columns: 5
  Media:
    style: row
    columns: 5
  Storage:
  Other:
