---
- name: Install modules
  with_items: "{{ modules }}"
  loop_control:
    loop_var: module
  ansible.builtin.include_tasks:
    file: module_install.yml
    apply:
      vars:
        module_name: "{{ module }}"
- name: Setup customizations
  ansible.builtin.template:
    src: customizations.nix
    dest: "{{ home_manager_root }}/customizations.nix"
  vars:
    modules_in_use: "{{ modules | select() | map('regex_replace', '^(.*)$', '    ./\\1/module.nix') | join('\n') }}"
- name: Check if customizations already imported 
  ansible.builtin.command:
    cmd: grep --quiet '# Ansible' '{{ home_manager_root }}/home.nix'
  register: home_nix_grep
  failed_when: false
  changed_when: false
- name: Add customizations to home.nix
  when: home_nix_grep.rc != 0
  ansible.builtin.shell:
    cmd: >-
      sed --in-place 's|^}$|\n  # Ansible\n  imports = [ ./customizations.nix ];\n}|g' '{{ home_manager_root }}/home.nix'
