---
- tags:
    - home-manager
  block:
    - tags:
        - install
        - no-ci
      block:
        - name: check if home-manager is installed
          environment:
            path: "{{ env_path }}"
          ansible.builtin.command:
            cmd: which home-manager
          register: installed
          failed_when: false
          changed_when: false
        - name: install home-manager
          when: installed.rc != 0
          ansible.builtin.include_tasks:
            file: install.yml
            apply: 
              environment:
                path: "{{ env_path }}"
    - name: Template modules
      tags: 
        - config
        - template
      ansible.builtin.include_tasks:
        file: template.yml
    - name: Import modules
      tags:
        - config
        - import
        - no-ci
      ansible.builtin.include_tasks:
        file: import.yml